typography_spectrum: 0.279684207867831
color:
  brandStrength: 0.981875468743965
  lightness: 0.37470896588638425
  saturation: 0.01781532820314169
  rhythmicContrast: 0.16342978598549962
  brandColors:
    - '#004358'
    - '#1F8A70'
    - '#BEDB39'
    - '#FFE11A'
    - '#FD7400'
opengraph:
  appId: 'https://www.facebook.com/crazyslowninja/'
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/38cf58fd-d8c5-4397-8878-2ece213a8986.png
layout_spectrum: 0.06811668095178902
author:
  name: Dave Sewell
  email: shooting@crazyslowninja
  url: www.crazyslowninja.com
name: CrazySlowNinja
