typography_spectrum: 0.279684207867831
color:
  brandStrength: 0.981875468743965
  lightness: 0.37470896588638425
  saturation: 0.01781532820314169
  rhythmicContrast: 0.16342978598549962
  brandColors:
    - '#004358'
    - '#1F8A70'
    - '#BEDB39'
    - '#FFE11A'
    - '#FD7400'
opengraph:
  appId: 'https://www.facebook.com/crazyslowninja/'
  image: null
layout_spectrum: 0.06811668095178902
author:
  name: Dave Sewell
  email: shooting@crazyslowninja
  url: www.crazyslowninja.com
name: CrazySlowNinja
title: The worst Xbox gamer in the world!
