typography_spectrum: 0.279684207867831
color:
  brandStrength: 0.17921293899416924
  lightness: 0.07051899912767112
  saturation: 0.3601939855143428
  rhythmicContrast: 0.13180113793350756
  brandColors:
    - '#85DB18'
    - '#CDE855'
    - '#F5F6D4'
    - '#A7C520'
    - '#493F0B'
opengraph:
  appId: 'https://www.facebook.com/crazyslowninja/'
  image: null
layout_spectrum: 0.06811668095178902
author:
  name: CrazySlow Ninja
  email: shooting@crazyslowninja
  url: www.crazyslowninja.com
name: CrazySlowNinja
title: The worst Xbox gamer in the world!
